config/routes.rb
Rails.application.routes.draw do

    root 'welcome#index'
    get '/auth/twitter', as: 'login'
    get '/auth/twitter/callback', to: 'sessions#create'
    get 'logout', to: 'sessions#destroy'
    get 'podcasts/search', to: 'podcasts#search'
    post 'podcasts/search_result', to: 'podcasts#search_result'
    get 'podcasts/search_result', to: 'podcasts#search_result'
    get 'playlists/selector', to: 'playlists#selector'

    get 'user/profile', to: 'users#show'

    resources :podcasts, only: [:new, :create, :destroy, :show]

    resources :playlists

end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
  belongs_to :user
  has_many :podcasts
end

app/models/podcast.rb
class Podcast < ActiveRecord::Base
  belongs_to :playlist

 validates :audiosearch_id, presence: true

  def self.create_podcast_on_a_playlist(params)
    podcast = self.new({
      audiosearch_id: params["audiosearch_id"],
      ep_title: params["ep_title"],
      description: params["description"],
      date_created_at: params["date_created_at"],
      show_title: params["show_title"],
      url: params["url"],
      image: params["image"],
      subject: params["subject"],
      playlist_id: params["playlist_id"]
      })
  end
end

app/models/podcast_playlist.rb
class PodcastPlaylist < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :playlists
  has_many :podcasts, through: :playlists

  def self.from_omniauth(auth_info)
   user = find_or_create_by(uid: auth_info.uid)

   user.update_attributes(
   name: auth_info.info.name,
   screen_name: auth_info.info.nickname,
   image: auth_info.info.image,
   oauth_token: auth_info.credentials.token,
   oauth_token_secret: auth_info.credentials.secret
   )
   user.save
   user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :current_playlist

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def current_playlist
    if session[:playlist]
      @playlist = Playlist.find(session[:playlist]["id"])
    elsif current_user && current_user.playlists.count == 1
      @playlist = current_user.playlists.first
    end
  end

end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController

  def index

    if current_user.playlists.empty?
      flash[:notice] = "Create a Playlist!"
      redirect_to new_playlist_path

    else
      @playlists = current_user.playlists
    end
  end

  def new

    @playlist = Playlist.new
  end

  def create
    @playlist = Playlist.create(subject: params["playlist"]["subject"], user_id: current_user.id)

    redirect_to playlists_path
  end

  def edit
  end

  def show
    @playlist = Playlist.find(params["id"])
    session[:playlist] = @playlist
  end

  def destroy
    Playlist.delete(params[:id])
    session[:playlist] = nil
    redirect_to new_playlist_path
  end
end

app/controllers/podcasts_controller.rb
class PodcastsController < ApplicationController
  before_action :store_query, only:[:search_result]

  def search

  end

  def search_result

    @results = AudiosearchService.new.search_by_query(params["podcast_subject"]["subject"])
  end

  def new
    if current_user.playlists.empty?
      flash[:notice] = "Create A Playlist!"
      redirect_to new_playlist_path
    else
      @podcast = Podcast.create_podcast_on_a_playlist(params['podcast'].merge({
        playlist_id: current_playlist.id}))
      if @podcast.save
        redirect_to playlist_path(@podcast.playlist)
      else
        flash[:notice] = "Fail Whale!"
        redirect_to new_playlist_path
      end
    end
  end

  def show
    begin
      @podcast = Podcast.find(params["id"]) || nil
      @related = AudiosearchService.new.search_by_related(@podcast.audiosearch_id)
    rescue ActiveRecord::RecordNotFound
      redirect_to podcasts_search_path
    end
  end

  def create
  end

  def destroy
    playlist_id = Playlist.find(session[:playlist]["id"]).id
    Podcast.delete(params["id"])
    redirect_to playlist_path(playlist_id)
  end

  private
    def store_query
      session[:subject] ||= params["podcast_subject"]["subject"]
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    if user = User.from_omniauth(request.env["omniauth.auth"])
      session[:user_id] = user.id
      redirect_to root_path
    else
      redirect_to root_path
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    if current_user
      @user = current_user
    else
      redirect_to root_path
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/views/layouts/_navbar.html.erb
<nav class="col-md-12 navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Ear Buddies</a>
    <ul class="nav navbar-nav">
      <li><%= link_to "All Your Playlists", playlists_path %></li>
      <li><%= link_to "Your Current Playlist is #{current_playlist.subject}", playlists_path unless current_playlist == nil %></li>
      <li><%= link_to "Search", podcasts_search_path %></li>
      <li><%= link_to "Create Playlist", new_playlist_path %></li>
      <li><%= link_to "Your Profile", user_profile_path %></li>
      <li><%= link_to "Logout", logout_path%></li>
        </ul>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <link rel="apple-touch-icon" sizes="57x57" href="/apple-touch-icon-57x57.png">
  <link rel="apple-touch-icon" sizes="60x60" href="/apple-touch-icon-60x60.png">
  <link rel="apple-touch-icon" sizes="72x72" href="/apple-touch-icon-72x72.png">
  <link rel="apple-touch-icon" sizes="76x76" href="/apple-touch-icon-76x76.png">
  <link rel="apple-touch-icon" sizes="114x114" href="/apple-touch-icon-114x114.png">
  <link rel="apple-touch-icon" sizes="120x120" href="/apple-touch-icon-120x120.png">
  <link rel="apple-touch-icon" sizes="144x144" href="/apple-touch-icon-144x144.png">
  <link rel="apple-touch-icon" sizes="152x152" href="/apple-touch-icon-152x152.png">
  <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon-180x180.png">
  <link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32">
  <link rel="icon" type="image/png" href="/android-chrome-192x192.png" sizes="192x192">
  <link rel="icon" type="image/png" href="/favicon-96x96.png" sizes="96x96">
  <link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16">
  <link rel="manifest" href="/manifest.json">
  <meta name="msapplication-TileColor" content="#da532c">
  <meta name="msapplication-TileImage" content="/mstile-144x144.png">
  <meta name="theme-color" content="#ffffff">

  <title>EarBuddies</title>
  <link href='https://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.min.css"
  rel="stylesheet" type="text/css">
</head>
<body>

  <% flash.each do |type, message| %>
    <div class="container alert alert-danger center alert-<%= type %>" role="alert">
      <%= message %>
    </div>
  <% end %>

<%= yield %>
<%= javascript_include_tag 'application' %>
</body>
</html>

app/views/playlists/index.html.erb
<%= render :partial => "layouts/navbar" %>

<div class="longboxed">
  <h1 class="funfont center"><font color="C71585"><%= current_user.name%>'s Playlists:</h1><br>
   <% @playlists.each do |playlist| %>
     <h2 class="funfont center"><%= link_to "#{playlist.subject}", playlist_path(playlist) %></h2>
     <div class="center"><%= button_to "Delete This Playlist", playlist_path(playlist.id), method: :delete, class: "btn btn-primary", data: { confirm: 'Are you sure?' }  %><br></div>
    <% end %>
  </div>

app/views/playlists/new.html.erb
<%= render :partial => "layouts/navbar" %>


  <div class="boxed">

<%= form_for @playlist do |f| %></h2>
<h1 class="funfont center"><%= f.label :playlist_name %></h1>
<h3 class="funfont center"><%= f.text_field :subject %></h3>
<h3 class="funfont center"><%= f.submit("Create Your Playlist") %></h3>
<% end %>

</div>
</div>

app/views/playlists/show.html.erb
<%= render :partial => "layouts/navbar" %>
<div class="container">
  <div class="newbox">
    <h1 class="funfont center"><%= @playlist.subject%></h1>
    <% if @playlist.podcasts == [] %>
    <h3><div class="center"><%= link_to "Search For Something Good", podcasts_search_path, method: :get, class: "btn btn-primary"%></h3>
    <% else %>
    <% @playlist.podcasts.each do |podcast| %>
    <h2 class="funfont center">More info about: <%= link_to "#{podcast.ep_title}", podcast_path(podcast.id) %> <br> From: <%= podcast.show_title %></h2>
    <h3 class="funfont center"><%= link_to "Listen Now", podcast.url, :class => "html5", :target => "_blank" %> </h3>
    <div class="center"><%= button_to "Remove Podcast From Playlist", podcast_path(podcast.id), method: :delete, class: "btn btn-secondary", data: { confirm: 'Are you sure?' }  %></div>

    <hr>
    <% end %>
    <% end %>

  </div>
</div>

app/views/podcasts/new.html.erb
<% current_user.playlists %>

app/views/podcasts/search.html.erb
<%= render :partial => "layouts/navbar" %>

<div class="container">
  <div class="well center funfont">
    <%= form_for :podcast_subject, :url => url_for(:controller => 'podcasts', :action => 'search_result') do |f| %>
    <h2 class="funfont"><%= f.label :What_Subject_Would_You_Like_To_Search %></h2>
    <%= f.text_field :subject %>
    <%= f.submit "Search" %>
    <% end %>
  </div>
</div>

app/views/podcasts/search_result.html.erb
<%= render :partial => "layouts/navbar" %>
<div class="container">
  <div class="newbox">


    <% @results.each do |result| %>
    <div class="card">
      <div class="card-block">
        <h3 class="card-title"><%= result[:ep_title]%></h4>
          <h6 class="card-subtitle text-muted">Podcast Publisher: <%= result[:show_title]%><br></h6>
        </div>
        <p class="card-text">Description <%= result[:description].first(140) unless result[:description] == nil%></p>
      <img src=<%=result[:image]%> alt="Card image">
        <div class="card-block">


          <div class="nothinghead"><%= link_to "Add To Playlist",
          new_podcast_path(result),
          class: "btn btn-primary btn-sm" %></div>

            <hr>
          </div>
        </div>

        <% end %>
      </div>
    </div>

app/views/podcasts/show.html.erb
<%= render :partial => "layouts/navbar" %>
<div class="container">
  <div class="newbox">
  <h2 class="funfont center">Episode Title: <%= @podcast.ep_title %></h2>
  <h3 class="funfont center ">Podcast Provider: <%= @podcast.show_title %></h3>
  <div class="center"><img src=<%= @podcast.image %>></div>
  Description: <%= @podcast.description.html_safe %><br>
  <br><br><br>


  <h2 class="funfont center">Related Episodes</h2>

  <% @related.each do |related_podcast| %>
    <h3 class="center"><%= related_podcast[:ep_title] %></h3>
    <div class="center"><%= link_to "Add To Playlist",
    new_podcast_path(related_podcast),
    class: "btn btn-primary btn-sm" %></div><br>
      <% end %>
    </div>
  </div>

app/views/podcasts_finder/new.html.erb
<div class="container">
  <div class="well center funfont">
    <%= form_for @podcast_subject, :url => url_for(:controller => 'podcasts_finder', :action => 'index') do |f| %>
    <h2 class="funfont"><%= f.label :What_Subject_Would_You_Like_To_Search %></h2>
    <%= f.text_field :subject %>
    <%= f.submit "Search" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="longboxed funfont center">

<h1 class="funfont center">Your Profile</h1>

<h2 class="funfont center"><%= @user.name %></h2><br>
<div class="center">

<img src=<%= @user.image %>></div><br>
<h2 class=funfont><%= link_to "Your Playlists", playlists_path %></h2>
</div>

app/views/welcome/_create_and_logout_buttons.html.erb
<%= link_to "Create A Playlist", new_playlist_path, class: "btn btn-primary" %>
<%= link_to "Logout", logout_path, class: "btn btn-primary"%>

app/views/welcome/_search_create_playlists_logout_buttons.html.erb
<%= link_to "Search", podcasts_search_path, class: "btn btn-primary"%>
<%= link_to "Create A Playlist", new_playlist_path, class: "btn btn-primary" %>
<%= link_to "Your Playlists", playlists_path, class: "btn btn-primary"%>
<%= link_to "Logout", logout_path, class: "btn btn-primary"%>

app/views/welcome/index.html.erb
<div class="container">
  <div class="well center">
   <h1 class="funfont">Ear Buddies</h1>
    <h4>Hello <%= current_user.name if current_user%></h4>
    <% if current_user && current_user.playlists != [] %>
     <%= render "search_create_playlists_logout_buttons" %>
    <% elsif current_user && current_user.playlists == [] %>
     <%= render "create_and_logout_buttons" %>
   <% else %>
    <%= link_to "Login", login_path, class: "btn btn-primary"%>
  <% end %>
 </div>
</div>